---
# tasks file for TP_INI

- name: "Rol: TP_INI - Grupo: Rejunte"
  debug:
    msg: "Inicio de tareas dentro del Rol: TP_INI"
             
- name: "Creo directorio para el archivo"
  file:
    path: /tmp/Grupo
    state: directory
    owner: vagrant

- name: "Creo el archivo desde template"
  template:
    src: template_01.j2
    dest: /tmp/Grupo/datos.txt
    owner: vagrant
